#
#	Supp-step 1: Check species count vs. correlation significance
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# for each of the treatment combinations that was found significant, and one that wasn't (for contrast)
trtGroups <- c("Plants.Water", "Plants", "Season")
for(i in 1:length(trtGroups)) {
	curTrtGroup <- strsplit(trtGroups[i], ".", fixed=T)
	curTrtGroup <- curTrtGroup[[1]]
	if (length(curTrtGroup) > 1) {
		fileName <- paste(curTrtGroup, collapse="_")
	}
	else {
		fileName <- curTrtGroup
	}
	# This file name (one for each treatment combination) is one of several generated by 'spearman.R'
	fileName <- paste("data/", fileName, "spearman.csv", sep="_")
	spearmanData <- read.csv(fileName, row.names=1, stringsAsFactors=F)
	
	# graphical parameters, which only affect the display of the data (not the data itself)
	par(mfrow=c(1,3), oma=c(2,0,2,0))

	plot(spearmanData$Species1Count, spearmanData$pValue, xlab="Taxon A count", ylab="p-Value")
	plot(spearmanData$Species2Count, spearmanData$pValue, xlab="Taxon B count", ylab="p-value")
	plot(abs(spearmanData$Species2Count - spearmanData$Species1Count), spearmanData$pValue, xlab="Taxon count difference", ylab="p-value")
	title("Taxon abundance vs. significance", outer=T)
}
q(save="no")


# TODO: Does species variance have an effect on significance.
