#
#	Step 7: Visiualize/analyze spearman correlations
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# '_Plants_spearman.csv' is one of many files generated by 'spearman.R'
spearmanData <- read.csv('data/_Plants_Water_spearman.csv', row.names=1)

# 'igraph' can both visualize and perform stats on -graph- objects
library(igraph)

# For positive correlations
significantSpearmanData <- subset(spearmanData, Coeff >= .75)

# 'graph.edgelist' takes a list of edges ('Species1' and 'Species2' from the 'spearman.R' results)
#  and makes it into an igraph graph object
exIr<-graph.edgelist(as.matrix(subset(significantSpearmanData, Treatment=="exotic irrigated")[,2:3]),directed=FALSE)
exNir<-graph.edgelist(as.matrix(subset(significantSpearmanData, Treatment=="exotic not irrigated")[,2:3]),directed=FALSE)
natIr<-graph.edgelist(as.matrix(subset(significantSpearmanData, Treatment=="native irrigated")[,2:3]),directed=FALSE)
natNir<-graph.edgelist(as.matrix(subset(significantSpearmanData, Treatment=="native not irrigated")[,2:3]),directed=FALSE)

V(exIr)$color <- "red"
V(exNir)$color <- "red"
V(natIr)$color<-"blue"
V(natNir)$color<-"blue"

V(exIr)$label<-NA
V(exNir)$label<-NA
V(natIr)$label<-NA
V(natNir)$label<-NA

E(exIr)$color<-"black"
E(exNir)$color<-"black"
E(natIr)$color<-"black"
E(natNir)$color<-"black"

V(exIr)$size<-8
V(exNir)$size<-8
V(natIr)$size<-8
V(natNir)$size<-8

plot(exIr,layout=layout.circle, main="Exotic Irrigated, Positive Correlations")
plot(exNir,layout=layout.circle, main="Exotic Not Irrigated, Positive Correlations")
plot(natIr,layout=layout.circle, main="Native Irrigated, Positive Correlations")
plot(natNir,layout=layout.circle, main="Native Not Irrigated, Positive Correlations")

# For positive correlations
significantSpearmanData <- subset(spearmanData, Coeff <= -.75)

# 'graph.edgelist' takes a list of edges ('Species1' and 'Species2' from the 'spearman.R' results)
#  and makes it into an igraph graph object
exIr<-graph.edgelist(as.matrix(subset(significantSpearmanData, Treatment=="exotic irrigated")[,2:3]),directed=FALSE)
exNir<-graph.edgelist(as.matrix(subset(significantSpearmanData, Treatment=="exotic not irrigated")[,2:3]),directed=FALSE)
natIr<-graph.edgelist(as.matrix(subset(significantSpearmanData, Treatment=="native irrigated")[,2:3]),directed=FALSE)
natNir<-graph.edgelist(as.matrix(subset(significantSpearmanData, Treatment=="native not irrigated")[,2:3]),directed=FALSE)

V(exIr)$color <- "red"
V(exNir)$color <- "red"
V(natIr)$color<-"blue"
V(natNir)$color<-"blue"

V(exIr)$label<-NA
V(exNir)$label<-NA
V(natIr)$label<-NA
V(natNir)$label<-NA

E(exIr)$color<-"black"
E(exNir)$color<-"black"
E(natIr)$color<-"black"
E(natNir)$color<-"black"

V(exIr)$size<-8
V(exNir)$size<-8
V(natIr)$size<-8
V(natNir)$size<-8

plot(exIr,layout=layout.circle, main="Exotic Irrigated, Negative Correlations")
plot(exNir,layout=layout.circle, main="Exotic Not Irrigated, Negative Correlations")
plot(natIr,layout=layout.circle, main="Native Irrigated, Negative Correlations")
plot(natNir,layout=layout.circle, main="Native Not Irrigated, Negative Correlations")

q(save="no")
